### ISSUE TITLE
TypeError: can't use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by sohimankotia** [RedisLabs/rejson-py#8]
Hi,

I am using python 3.4 and following code 

```
from rejson import Client, Path

rj = Client(host='localhost', port=6379)

# Set the key `obj` to some object
obj = {
    'answer': 42,
    'arr': [None, True, 3.14],
    'truth': {
        'coord': 'out there'
    }
}
rj.jsonset('obj', Path.rootPath(), obj)

# Get something
response = rj.jsonget('obj', Path('.truth.coord'))
print (response.read().decode('utf-8'))

```

Value is getting inserted but while reading it is throwing following error 

```
Traceback (most recent call last):
  File "/home/sohanvir/pyhton-workspace/rejsonDemo.py", line 16, in <module>
    response = rj.jsonget('obj', Path('.truth.coord'))
  File "/usr/local/lib/python3.4/dist-packages/rejson/client.py", line 114, in jsonget
    return self.execute_command('JSON.GET', *pieces)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 587, in parse_response
    return self.response_callbacks[command_name](response, **options)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: can't use a string pattern on a bytes-like object
```

**Comment by sohimankotia** [comment]
Solved . Hade to enable decode_response

`rj = Client(host='localhost',port=6379,db=0,decode_responses=True)`

**Comment by sohimankotia** [comment]
Resolved my self .

**Comment by mmlb** [comment]
I just came across this same error, it seems to me that on python3 `Client` should set `decode_responses=True`, having a bad default that makes the simplest `jsonget` fail isn't very nice.

```py
from __future__ import print_function
from rejson import Client, Path
rj = Client()
# Set the key `obj` to some object
obj = {'answer': 42, 'arr': [None, True, 3.14], 'truth': {'coord': 'out there'}}
rj.jsonset('obj', Path.rootPath(), obj)
print(rj.jsonget('obj', Path('.truth.coord'))) # ok
print(rj.jsonget('obj', Path.rootPath())) # raises :(
```

**Comment by dvirsky** [comment]
@mmlb care to make a PR?

**Comment by healiseu** [comment]
I don't think it's a good idea to close this issue, this kind of error will appear to all newcomers that use Python 3 and @mmlb is right the decode_responses=True should have been added as a default parameter. It's also not documented and that makes it even more difficult to figure out how to solve this problem.

**Comment by stsievert** [comment]
:+1: to this issue – it took me too long to find https://github.com/RedisLabs/rejson-py/issues/8#issuecomment-321514267. I added `decode_responses=True` to the example in the README.
